// Generated by https://quicktype.io
export  interface loginData{
    correo:string;
    password:string;
}


export  interface registerData{
    correo:string;
    password:string;
    nombre:string
}
export interface LoginResponse{
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img?:   string;
}


import { ImageSourcePropType } from "react-native";
export interface MenuItem{
        
    name:string
    icon:string
    components:string
}



export interface Slide {
    title: string;
    desc: string;
    img: ImageSourcePropType
}

//productos

// Generated by https://quicktype.io

export interface ProductsResponse {
    total:     number;
    productos: Producto[];
}

export interface Producto {
    precio:    number;
    _id:       string;
    nombre:    string;
    categoria: Categoria;
    usuario:   Categoria;
    img?:      string;
}


// Generated by https://quicktype.io

export interface CategoriesResponse {
    total:      number;
    categorias: Categoria[];
}

export interface Categoria {
    _id:     string;
    nombre:  string;
    usuario?: UsuarioCategoria;
}

export interface UsuarioCategoria {
    _id:    string;
    nombre: string;
}
